language: cpp

os: linux
dist: xenial

env:
  - PATH=/opt/qt56/bin:/usr/local/opt/qt5/bin:$PATH

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt563-xenial'
    packages:
      - qt56base
      - libgl1-mesa-dev

script:
  - qmake ./src && make -j4
