name: Build Linux

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: "Build: ${{ matrix.os }} - ${{ matrix.qtver }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        arch: [x64]
        config: [Release]
        include:
          - qtver: Qt6
            host_triplet: release

    steps:
    - name: Checkout Git Repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: workaround for default apt mirror connectivity issues
      run: |
        sudo sed -i 's/azure\.//' /etc/apt/sources.list

    - name: Install dependencies
      run: |
        set -e
        sudo apt install -y autoconf automake autoconf-archive '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libegl1-mesa-dev libudev-dev libusb-1.0-0-dev

    - name: Install latest CMake
      uses: lukka/get-cmake@a70f1cfa1857a3eecfe0d34962269e1b1e8be56c # latest as of 2024-08-08

    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@d87e7fac99f22776a4973d7e413921ea254c1fc9 # latest as of 2024-08-08
      with:
        vcpkgJsonGlob: '**/src/vcpkg.json'

    - name: Build Oiram Editor ${{ matrix.qtver }} ${{ matrix.config }} on Linux ${{ matrix.arch }}
      uses: lukka/run-cmake@4b1adc1944be8367be9f4e08303ce49918db8e3c # latest as of 2024-08-08
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/src/CMakeLists.txt'
        configurePreset: 'Linux-${{ matrix.arch }}-${{ matrix.qtver }}'
        configurePresetAdditionalArgs: "['-DDEPS_RELEASE_ONLY=ON']"
        buildPreset: 'Linux-${{ matrix.arch }}-${{ matrix.qtver }}-${{ matrix.config }}'
      env:
        VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.arch }}-linux-${{ matrix.host_triplet }}
        VCPKG_FORCE_SYSTEM_BINARIES: 1

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v3
      with:
        name: oriam_editor_linux_${{ matrix.qtver }}_master
        path: ${{ github.workspace }}/src/oiram-editor.build/Linux-${{ matrix.arch }}-${{ matrix.qtver }}/${{ matrix.config }}/oiram-editor
